=== gabadie/xmlparser/tests/xsd_files/9_occurs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="person" type="personType"/>

    <xs:complexType name="personType">
        <xs:element ref="infos"/>
    </xs:complexType>

    <xs:element name="infos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="surname" minOccurs="2" maxOccurs="unbounded"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="birth" type="xs:date"/>
                <xs:choice minOccurs="2" maxOccurs="5">
                    <xs:element name="tel" type="xs:string"/>
                    <xs:choice>
                        <xs:element name="patate" type="xs:string"/>
                        <xs:element name="pomme" type="xs:string"/>
                    </xs:choice>
                    <xs:element name="mobile" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="validity" use="required"/>
            <xs:attribute name="invalidity" type="xs:date" use="required"/>
            <xs:attribute name="test" type="xs:string"/>
            <xs:attribute name="test2" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="validity" type="xs:date"/>

    <xs:element name="surname" type="xs:string"/>
</xs:schema>

=== gabadie/xmlparser/tests/xml_files/9_occurs.xml
<?xml version="1.0" encoding="UTF-8"?>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd_files/9_occurs.xsd">
    <infos validity="02-05-2014" invalidity="02-05-2018" test="patate">
        <surname>Kin1</surname>
        <surname>King2</surname>
        <surname>King3</surname>
        <surname>King4</surname>
        <name>Julian</name>
        <mobile>lalala</mobile>
        <patate>lalala</patate>
        <pomme>lalala</pomme>
    </infos>
</person>
